name: Build SVT-AV1
description: Create highly optimised Windows, Linux, and macOS builds for SVT-AV1
author: Akatsumekusa, Yiss, and contributors
inputs:
  path:
    type: string
    default: "."

  static:
    type: string
    default: "true"

  shared:
    type: string
    default: "false"

  pgo-video:
    type: string
    default: "SolLevante"

  pgo-parameters:
    type: string
    default: "--crf 20 --tune 0"

  base-arch-only:
    type: string
    default: "false"

  dovi-hdr10plus:
    type: string
    default: "true"

  ffms2:
    type: string
    default: "false"

  cmakeflags:
    type: string
    default: ""

  cflags-profiling:
    type: string
    default: ""
  ldflags-profiling:
    type: string
    default: ""
  cflags-final:
    type: string
    default: ""
  ldflags-final:
    type: string
    default: ""

runs:
  using: composite
  steps:


  - uses: msys2/setup-msys2@v2.32.0
    with:
      msystem: CLANG64
      path-type: inherit
      install: >-
        mingw-w64-clang-x86_64-fastfetch
        fish
    if: ${{ runner.os == 'Windows' && runner.arch == 'X64' }}
  - uses: msys2/setup-msys2@v2.32.0
    with:
      msystem: CLANGARM64
      path-type: inherit
      install: >-
        mingw-w64-clang-aarch64-fastfetch
        fish
    if: ${{ runner.os == 'Windows' && runner.arch == 'ARM64' }}
  - uses: ConorMacBride/install-package@v1
    with:
      apt: neofetch fish
    if: ${{ runner.os == 'Linux' }}
  - uses: ConorMacBride/install-package@v1
    with:
      brew: fastfetch fish
    if: ${{ runner.os == 'macOS' }}
  - run: fastfetch
    shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
    if: ${{ runner.os == 'Windows' || runner.os == 'macOS' }}
  - run: neofetch
    shell: bash
    if: ${{ runner.os == 'Linux' }}


  - name: Setup FFmpeg
    uses: AnimMouse/setup-ffmpeg@v1
    if: ${{ inputs.pgo-video != 'false' }}
  - uses: actions/checkout@v7
    with:
      path: ${{ inputs.path }}/PGO
      repository: Akatmks/build-svt-av1
      ref: ${{ inputs.pgo-video }}
    if: ${{ inputs.pgo-video != 'false' }}
  - run: cat PGO.mkv.* > PGO.mkv
    shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
    working-directory: ${{ inputs.path }}/PGO
    if: ${{ inputs.pgo-video != 'false' }}
  - run: ffmpeg -i PGO.mkv -strict -1 -f yuv4mpegpipe -pix_fmt yuv420p10le PGO.y4m
    shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
    working-directory: ${{ inputs.path }}/PGO
    if: ${{ inputs.pgo-video != 'false' }}


  - uses: ilammy/setup-nasm@v1
    if: ${{ runner.arch == 'X64' }}
  - uses: ZhongRuoyu/setup-llvm@v0
    if: ${{ (runner.os == 'Windows' && runner.arch == 'X64') || runner.os == 'Linux' }}
  # This needs to be updated when we're approaching LLVM version 30. Hope ZhongRuoyu/setup-llvm supports Windows arm64 by then.
  - id: install-llvm-30
    uses: KyleMayes/install-llvm-action@v2
    with:
      version: 30
    continue-on-error: true
    if: ${{ runner.os == 'Windows' && runner.arch == 'ARM64' }}
  - id: install-llvm-29
    uses: KyleMayes/install-llvm-action@v2
    with:
      version: 29
    continue-on-error: true
    if: ${{ runner.os == 'Windows' && runner.arch == 'ARM64' && steps.install-llvm-30.outcome == 'failure' }}
  - id: install-llvm-28
    uses: KyleMayes/install-llvm-action@v2
    with:
      version: 28
    continue-on-error: true
    if: ${{ runner.os == 'Windows' && runner.arch == 'ARM64' && steps.install-llvm-29.outcome == 'failure' }}
  - id: install-llvm-27
    uses: KyleMayes/install-llvm-action@v2
    with:
      version: 27
    continue-on-error: true
    if: ${{ runner.os == 'Windows' && runner.arch == 'ARM64' && steps.install-llvm-28.outcome == 'failure' }}
  - id: install-llvm-26
    uses: KyleMayes/install-llvm-action@v2
    with:
      version: 26
    continue-on-error: true
    if: ${{ runner.os == 'Windows' && runner.arch == 'ARM64' && steps.install-llvm-27.outcome == 'failure' }}
  - id: install-llvm-25
    uses: KyleMayes/install-llvm-action@v2
    with:
      version: 25
    continue-on-error: true
    if: ${{ runner.os == 'Windows' && runner.arch == 'ARM64' && steps.install-llvm-26.outcome == 'failure' }}
  - id: install-llvm-24
    uses: KyleMayes/install-llvm-action@v2
    with:
      version: 24
    continue-on-error: true
    if: ${{ runner.os == 'Windows' && runner.arch == 'ARM64' && steps.install-llvm-25.outcome == 'failure' }}
  - id: install-llvm-23
    uses: KyleMayes/install-llvm-action@v2
    with:
      version: 23
    continue-on-error: true
    if: ${{ runner.os == 'Windows' && runner.arch == 'ARM64' && steps.install-llvm-24.outcome == 'failure' }}
  - id: install-llvm-22
    uses: KyleMayes/install-llvm-action@v2
    with:
      version: 22
    continue-on-error: true
    if: ${{ runner.os == 'Windows' && runner.arch == 'ARM64' && steps.install-llvm-23.outcome == 'failure' }}
  - id: install-llvm-21
    uses: KyleMayes/install-llvm-action@v2
    with:
      version: 21
    continue-on-error: true
    if: ${{ runner.os == 'Windows' && runner.arch == 'ARM64' && steps.install-llvm-22.outcome == 'failure' }}
  - uses: KyleMayes/install-llvm-action@v2
    with:
      version: 20
    if: ${{ runner.os == 'Windows' && runner.arch == 'ARM64' && steps.install-llvm-21.outcome == 'failure' }}
  # Remeber to check latest Homebrew LLVM weirdness
  - run: brew install llvm lld
    shell: bash
    if: ${{ runner.os == 'macOS' }}
  - uses: lukka/get-cmake@latest
    if: ${{ runner.os == 'Windows' }}
  - run: pacman --noconfirm -S --needed mingw-w64-clang-x86_64-pkgconf
    shell: msys2 {0}
    if: ${{ runner.os == 'Windows' && runner.arch == 'X64' }}
  - run: pacman --noconfirm -S --needed mingw-w64-clang-aarch64-pkgconf
    shell: msys2 {0}
    if: ${{ runner.os == 'Windows' && runner.arch == 'ARM64' }}


  - uses: dtolnay/rust-toolchain@stable
    if: ${{ inputs.dovi-hdr10plus != 'false' }}
  - uses: cargo-bins/cargo-binstall@main
    if: ${{ inputs.dovi-hdr10plus != 'false' }}
  - run: cargo binstall cargo-c
    shell: msys2 {0}
    if: ${{ runner.os == 'Windows' && inputs.dovi-hdr10plus != 'false' }}
  - run: cargo binstall cargo-c
    shell: bash
    if: ${{ runner.os != 'Windows' && inputs.dovi-hdr10plus != 'false' }}
  - uses: robinraju/release-downloader@v1
    with:
      repository: quietvoid/dovi_tool
      latest: true
      tarBall: true
      out-file-path: ${{ inputs.path }}/deps/src/dovi_tool
    if: ${{ inputs.dovi-hdr10plus != 'false' }}
  - run: tar -xz --strip-components=1 -f *.tar.gz
    shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
    working-directory: ${{ inputs.path }}/deps/src/dovi_tool
    if: ${{ inputs.dovi-hdr10plus != 'false' }}
  - run: cd dolby_vision && RUSTFLAGS="-Ctarget-cpu=x86-64-v3 -Copt-level=3" cargo cinstall --verbose --release --library-type staticlib --prefix "$(cygpath -m -a ../../../install)"
    shell: msys2 {0}
    working-directory: ${{ inputs.path }}/deps/src/dovi_tool
    if: ${{ runner.os == 'Windows' && runner.arch == 'X64' && inputs.dovi-hdr10plus != 'false' }}
  - run: cd dolby_vision && RUSTFLAGS="-Ctarget-cpu=oryon-1 -Copt-level=3" cargo cinstall --verbose --release --library-type staticlib --prefix "$(cygpath -m -a ../../../install)"
    shell: msys2 {0}
    working-directory: ${{ inputs.path }}/deps/src/dovi_tool
    if: ${{ runner.os == 'Windows' && runner.arch == 'ARM64' && inputs.dovi-hdr10plus != 'false' }}
  - run: cd dolby_vision && RUSTFLAGS="-Ctarget-cpu=x86-64-v3 -Copt-level=3" cargo cinstall --verbose --release --library-type staticlib --prefix "$(realpath ../../..)/install"
    shell: bash
    working-directory: ${{ inputs.path }}/deps/src/dovi_tool
    if: ${{ runner.os == 'Linux' && runner.arch == 'X64' && inputs.dovi-hdr10plus != 'false' }}
  - run: cd dolby_vision && RUSTFLAGS="-Ctarget-cpu=apple-m1 -Copt-level=3" cargo cinstall --verbose --release --library-type staticlib --prefix "$(realpath ../../..)/install"
    shell: bash
    working-directory: ${{ inputs.path }}/deps/src/dovi_tool
    if: ${{ runner.os == 'macOS' && runner.arch == 'ARM64' && inputs.dovi-hdr10plus != 'false' }}
  - run: cd dolby_vision && RUSTFLAGS="-Ctarget-cpu=skylake -Copt-level=3" cargo cinstall --verbose --release --library-type staticlib --prefix "$(realpath ../../..)/install"
    shell: bash
    working-directory: ${{ inputs.path }}/deps/src/dovi_tool
    if: ${{ runner.os == 'macOS' && runner.arch == 'X64' && inputs.dovi-hdr10plus != 'false' }}
  - uses: robinraju/release-downloader@v1
    with:
      repository: quietvoid/hdr10plus_tool
      latest: true
      tarBall: true
      out-file-path: ${{ inputs.path }}/deps/src/hdr10plus_tool
    if: ${{ inputs.dovi-hdr10plus != 'false' }}
  - run: tar -xz --strip-components=1 -f *.tar.gz
    shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
    working-directory: ${{ inputs.path }}/deps/src/hdr10plus_tool
    if: ${{ inputs.dovi-hdr10plus != 'false' }}
  - run: cd hdr10plus && RUSTFLAGS="-Ctarget-cpu=x86-64-v3 -Copt-level=3" cargo cinstall --verbose --release --library-type staticlib --prefix "$(cygpath -m -a ../../../install)"
    shell: msys2 {0}
    working-directory: ${{ inputs.path }}/deps/src/hdr10plus_tool
    if: ${{ runner.os == 'Windows' && runner.arch == 'X64' && inputs.dovi-hdr10plus != 'false' }}
  - run: cd hdr10plus && RUSTFLAGS="-Ctarget-cpu=oryon-1 -Copt-level=3" cargo cinstall --verbose --release --library-type staticlib --prefix "$(cygpath -m -a ../../../install)"
    shell: msys2 {0}
    working-directory: ${{ inputs.path }}/deps/src/hdr10plus_tool
    if: ${{ runner.os == 'Windows' && runner.arch == 'ARM64' && inputs.dovi-hdr10plus != 'false' }}
  - run: cd hdr10plus && RUSTFLAGS="-Ctarget-cpu=x86-64-v3 -Copt-level=3" cargo cinstall --verbose --release --library-type staticlib --prefix "$(realpath ../../..)/install"
    shell: bash
    working-directory: ${{ inputs.path }}/deps/src/hdr10plus_tool
    if: ${{ runner.os == 'Linux' && runner.arch == 'X64' && inputs.dovi-hdr10plus != 'false' }}
  - run: cd hdr10plus && RUSTFLAGS="-Ctarget-cpu=apple-m1 -Copt-level=3" cargo cinstall --verbose --release --library-type staticlib --prefix "$(realpath ../../..)/install"
    shell: bash
    working-directory: ${{ inputs.path }}/deps/src/hdr10plus_tool
    if: ${{ runner.os == 'macOS' && runner.arch == 'ARM64' && inputs.dovi-hdr10plus != 'false' }}
  - run: cd hdr10plus && RUSTFLAGS="-Ctarget-cpu=skylake -Copt-level=3" cargo cinstall --verbose --release --library-type staticlib --prefix "$(realpath ../../..)/install"
    shell: bash
    working-directory: ${{ inputs.path }}/deps/src/hdr10plus_tool
    if: ${{ runner.os == 'macOS' && runner.arch == 'X64' && inputs.dovi-hdr10plus != 'false' }}


  - uses: actions/checkout@v7
    with:
      path: ${{ inputs.path }}/deps/src/ffms2
      repository: Uranite/ffms2
    if: ${{ runner.os == 'Windows' && inputs.ffms2 != 'false' }}
  - run: pip install meson
    shell: pwsh
    if: ${{ runner.os == 'Windows' && inputs.ffms2 != 'false' }}
  - uses: ilammy/msvc-dev-cmd@v1
    if: ${{ runner.os == 'Windows' && inputs.ffms2 != 'false' }}
    with:
      arch: ${{ runner.arch == 'ARM64' && 'arm64' || 'x64' }}
  - name: Build FFMS2 and dependencies
    shell: msys2 {0}
    working-directory: ${{ inputs.path }}/deps/src
    if: ${{ runner.os == 'Windows' && inputs.ffms2 != 'false' }}
    env:
      ARCH_CFLAGS: ${{ runner.arch == 'ARM64' && '-march=armv8.7-a+crypto+sm4+sha3+fp16+sve+sve2 -mtune=oryon-1' || '-march=x86-64-v3 -mtune=znver2' }}
    run: |
      export CC="clang"
      export CXX="clang++"
      
      git clone --depth 1 https://github.com/madler/zlib.git
      cd zlib
      cmake --fresh -B zlib_build -G Ninja -DZLIB_BUILD_SHARED=OFF -DZLIB_BUILD_STATIC=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded -DCMAKE_C_FLAGS_RELEASE="-flto -O3 -DNDEBUG ${ARCH_CFLAGS}" -DCMAKE_INSTALL_PREFIX="$(pwd)/../../install"
      cmake --build zlib_build
      cmake --install zlib_build
      cd ..
      
      git clone --depth 1 https://code.videolan.org/videolan/dav1d.git
      cd dav1d
      meson setup build --prefix="$(pwd)/../../install" --default-library=static --buildtype=release -Db_vscrt=mt -Db_lto=true -Doptimization=3 -Denable_tools=false -Denable_examples=false -Dc_args="-DNDEBUG ${ARCH_CFLAGS}" -Dc_link_args="-fuse-ld=lld"
      meson install -C build
      mv ../../install/lib/libdav1d.a ../../install/lib/dav1d.lib || true
      cd ..
      
      git clone --depth 1 https://github.com/FFmpeg/FFmpeg.git
      cd FFmpeg
      export PKG_CONFIG_PATH="$(pwd)/../../install/lib/pkgconfig:$PKG_CONFIG_PATH"
      sed -i 's/if test "$cc_type" = "clang"; then/if true; then/' configure
      sed -i 's/test "$cc_type" != "$ld_type" && die "LTO requires same compiler and linker"/true/' configure
      sed -i "s/grep -qE 'LNK4044|lld-link: warning: ignoring unknown argument'/false/" configure
      sed -i 's/echo zlib.lib ;;/echo zs.lib ;;/' configure
      sed -i 's|gsub(/\\\\/, "/");|gsub(/\\\\\\\\/, "/");|' configure
      
      export INCLUDE="$(cygpath -m "$(pwd)/../../install/include");$INCLUDE"
      export LIB="$(cygpath -m "$(pwd)/../../install/lib");$LIB"
      
      ./configure \
          --prefix="$(pwd)/../../install" \
          --cc="clang-cl" \
          --cxx="clang-cl" \
          --as="clang-cl" \
          --ld="lld-link" \
          --ar="llvm-ar" \
          --ranlib="llvm-ranlib" \
          --nm="llvm-nm" \
          --strip="llvm-strip" \
          --toolchain="msvc" \
          --enable-lto="full" \
          --extra-cflags="-flto -DNDEBUG ${ARCH_CFLAGS} /clang:-O3" \
          --extra-libs="dav1d.lib zs.lib" \
          --disable-shared \
          --enable-static \
          --pkg-config-flags="--static" \
          --disable-programs --disable-doc --disable-network --disable-autodetect \
          --disable-debug --disable-encoders --disable-muxers --disable-filters \
          --disable-avfilter --disable-devices --disable-hwaccels \
          --enable-libdav1d --enable-zlib || (cat ffbuild/config.log; exit 1)
      make -j$(nproc)
      make install
      cd ..
      
      for pc in ../install/lib/pkgconfig/*.pc; do
          sed -i 's/-libpath:/-L/g' "$pc"
          sed -i 's/ \([a-zA-Z0-9_\-]*\)\.lib/ -l\1/g' "$pc"
      done
      
      cd ffms2
      cmake -B build_ffms2 -G Ninja -DCMAKE_BUILD_TYPE=Release -DENABLE_AVISYNTH=OFF -DENABLE_VAPOURSYNTH=OFF -DBUILD_SHARED_LIBS=OFF -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded -DCMAKE_CXX_FLAGS="-flto -O3 -DNDEBUG ${ARCH_CFLAGS}" -DCMAKE_C_FLAGS="-flto -O3 -DNDEBUG ${ARCH_CFLAGS}" -DZLIB_LIBRARY="$(pwd)/../../install/lib/zs.lib" -DCMAKE_INSTALL_PREFIX="$(pwd)/../../install"
      cmake --build build_ffms2
      cmake --install build_ffms2
  - run: sudo apt install -y libffms2-5 libffms2-dev
    shell: bash
    if: ${{ runner.os == 'Linux' && inputs.ffms2 != 'false' }}
  - run: brew install ffms2
    shell: bash
    if: ${{ runner.os == 'macOS' && inputs.ffms2 != 'false' }}


  - run: sed -i "s/ --dirty / /g" Source/Lib/Codec/ConfigureGitVersion.cmake
    shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
    working-directory: ${{ inputs.path }}
    continue-on-error: true
    if: ${{ runner.os != 'macOS' }}
  - run: sed -i "" "s/ --dirty / /g" Source/Lib/Codec/ConfigureGitVersion.cmake
    shell: bash
    working-directory: ${{ inputs.path }}
    continue-on-error: true
    if: ${{ runner.os == 'macOS' }}
  - run: fish "$GITHUB_ACTION_PATH/build.fish" --os=${{ runner.os }} --arch=${{ runner.arch }} --static=${{ inputs.static }} --shared=${{ inputs.shared }} --pgo-parameters='${{ inputs.pgo-parameters }}' --base-arch-only=${{ inputs.base-arch-only }} --dovi-hdr10plus=${{ inputs.dovi-hdr10plus }} --ffms2=${{ inputs.ffms2 }} --cmakeflags='${{ inputs.cmakeflags }}' --cflags-profiling='${{ inputs.cflags-profiling }}' --ldflags-profiling='${{ inputs.ldflags-profiling }}' --cflags-final='${{ inputs.cflags-final }}' --ldflags-final='${{ inputs.ldflags-final }}'
    shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
    working-directory: ${{ inputs.path }}
